#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : unifdef
Version  : 2.12
Release  : 7
URL      : http://dotat.at/prog/unifdef/unifdef-2.12.tar.xz
Source0  : http://dotat.at/prog/unifdef/unifdef-2.12.tar.xz
Summary  : Remove #ifdef'ed lines
Group    : Development/Tools
License  : BSD-3-Clause
Requires: unifdef-license = %{version}-%{release}

%description
unifdef - selectively remove C preprocessor conditionals
Written by Tony Finch <dot@dotat.at> - http://dotat.at/prog/unifdef/

%package license
Summary: license components for the unifdef package.
Group: Default

%description license
license components for the unifdef package.


%prep
%setup -q -n unifdef-2.12
cd %{_builddir}/unifdef-2.12

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1581707564
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1581707564
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/unifdef
cp %{_builddir}/unifdef-2.12/COPYING %{buildroot}/usr/share/package-licenses/unifdef/deece2df37f0496129ff6d1c8da988bf69d58311
%make_install
## install_append content
mv %{buildroot}/builddir %{buildroot}/usr
## install_append end

%files
%defattr(-,root,root,-)
/usr/builddir/bin/unifdef
/usr/builddir/bin/unifdefall
/usr/builddir/share/man/man1/unifdef.1
/usr/builddir/share/man/man1/unifdefall.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/unifdef/deece2df37f0496129ff6d1c8da988bf69d58311
