#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : unifdef
Version  : 2.11
Release  : 2
URL      : http://dotat.at/prog/unifdef/unifdef-2.11.tar.xz
Source0  : http://dotat.at/prog/unifdef/unifdef-2.11.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause

%description
unifdef - selectively remove C preprocessor conditionals
Written by Tony Finch <dot@dotat.at> - http://dotat.at/prog/unifdef/

%prep
%setup -q -n unifdef-2.11

%build
export LANG=C
make V=1  %{?_smp_mflags}

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
/builddir/bin/unifdef
/builddir/bin/unifdefall
/builddir/share/man/man1/unifdef.1
/builddir/share/man/man1/unifdefall.1
